import web3 from './web3';

const address ='0xe54baf1f648398bda92945df0b568587f089e2b0';
const abi = [
   {
      "constant":true,
      "inputs":[
         {
            "name":"",
            "type":"address"
         }
      ],
      "name":"vehicles",
      "outputs":[
         {
            "name":"",
            "type":"bool"
         }
      ],
      "payable":false,
      "stateMutability":"view",
      "type":"function"
   },
   {
      "constant":false,
      "inputs":[
         {
            "name":"necessityIndex",
            "type":"uint256"
         },
         {
            "name":"confirmed",
            "type":"bool"
         }
      ],
      "name":"confirmNecessityFullFillment",
      "outputs":[

      ],
      "payable":false,
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "constant":false,
      "inputs":[
         {
            "name":"manager",
            "type":"address"
         }
      ],
      "name":"registerManager",
      "outputs":[

      ],
      "payable":false,
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "constant":false,
      "inputs":[
         {
            "name":"necessityIndex",
            "type":"uint256"
         }
      ],
      "name":"fullfillNecessity",
      "outputs":[

      ],
      "payable":false,
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "constant":false,
      "inputs":[

      ],
      "name":"registerUser",
      "outputs":[

      ],
      "payable":true,
      "stateMutability":"payable",
      "type":"function"
   },
   {
      "constant":false,
      "inputs":[
         {
            "name":"vehicle",
            "type":"address"
         }
      ],
      "name":"registerVehicle",
      "outputs":[

      ],
      "payable":false,
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "constant":true,
      "inputs":[

      ],
      "name":"getUsagesNumber",
      "outputs":[
         {
            "name":"",
            "type":"uint256"
         }
      ],
      "payable":false,
      "stateMutability":"view",
      "type":"function"
   },
   {
      "constant":true,
      "inputs":[
         {
            "name":"",
            "type":"uint256"
         }
      ],
      "name":"necessities",
      "outputs":[
         {
            "name":"principal",
            "type":"address"
         },
         {
            "name":"description",
            "type":"string"
         },
         {
            "name":"value",
            "type":"uint256"
         },
         {
            "name":"contractor",
            "type":"address"
         },
         {
            "name":"demanded",
            "type":"bool"
         },
         {
            "name":"confirmed",
            "type":"bool"
         }
      ],
      "payable":false,
      "stateMutability":"view",
      "type":"function"
   },
   {
      "constant":true,
      "inputs":[

      ],
      "name":"getNecessitiesNumber",
      "outputs":[
         {
            "name":"",
            "type":"uint256"
         }
      ],
      "payable":false,
      "stateMutability":"view",
      "type":"function"
   },
   {
      "constant":true,
      "inputs":[
         {
            "name":"",
            "type":"address"
         }
      ],
      "name":"users",
      "outputs":[
         {
            "name":"",
            "type":"bool"
         }
      ],
      "payable":false,
      "stateMutability":"view",
      "type":"function"
   },
   {
      "constant":true,
      "inputs":[
         {
            "name":"",
            "type":"uint256"
         }
      ],
      "name":"usages",
      "outputs":[
         {
            "name":"principal",
            "type":"address"
         },
         {
            "name":"description",
            "type":"string"
         },
         {
            "name":"value",
            "type":"uint256"
         },
         {
            "name":"complete",
            "type":"bool"
         },
         {
            "name":"contractor",
            "type":"address"
         }
      ],
      "payable":false,
      "stateMutability":"view",
      "type":"function"
   },
   {
      "constant":false,
      "inputs":[
         {
            "name":"usageIndex",
            "type":"uint256"
         }
      ],
      "name":"payForUsage",
      "outputs":[

      ],
      "payable":true,
      "stateMutability":"payable",
      "type":"function"
   },
   {
      "constant":false,
      "inputs":[
         {
            "name":"description",
            "type":"string"
         },
         {
            "name":"value",
            "type":"uint256"
         }
      ],
      "name":"createNecessity",
      "outputs":[

      ],
      "payable":false,
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "constant":false,
      "inputs":[
         {
            "name":"description",
            "type":"string"
         },
         {
            "name":"value",
            "type":"uint256"
         },
         {
            "name":"contractor",
            "type":"address"
         }
      ],
      "name":"registerUsage",
      "outputs":[

      ],
      "payable":false,
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "constant":true,
      "inputs":[

      ],
      "name":"minimalFee",
      "outputs":[
         {
            "name":"",
            "type":"uint256"
         }
      ],
      "payable":false,
      "stateMutability":"view",
      "type":"function"
   },
   {
      "constant":true,
      "inputs":[
         {
            "name":"",
            "type":"address"
         }
      ],
      "name":"managers",
      "outputs":[
         {
            "name":"",
            "type":"bool"
         }
      ],
      "payable":false,
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "name":"minimum",
            "type":"uint256"
         }
      ],
      "payable":false,
      "stateMutability":"nonpayable",
      "type":"constructor"
   }
];

export default new web3.eth.Contract(abi, address);